### ISSUE TITLE
PLugin setting chrash my game

### ISSUE THREAD

**Issue by R3TR0V1P3R** [KieranCanter/FlipReady#5]
When i go to check the setting under bakkes mod it crashes my game and it never shows up in training or in game

**Comment by kicanter** [comment]
Can you give steps to recreate? I don't know what setting you're referring to.

**Comment by R3TR0V1P3R** [comment]
> Can you give steps to recreate? I don't know what setting you're referring to.

So the settings I'm referring to are all of them. When I click on your plugin to change the settings it completely crashes my game. Like I can't even see what setting there are as soon as I click on your plugin in bakkes mod it crashes my game I hope that I made it more clear like it not one setting it's the entire settings it self. Also I did wanna say that I really appreciate you getting back to me so fast. I really like to see that it mod creators 

Sincerely, Cody
